title: Trisham Patil
description: AI Engineer | Backend Engineer | LLM Engineering | MLOps | System Design & Architecture
url: "https://trishambp.github.io"
baseurl: ""

theme: minima

email: trishampatil@gmail.com

github_username: TrishamBP
linkedin_username: trishampatil

header_pages:
  - about.md
  - projects.md
  - blog.md
  - resume.md

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"
